# .circleci/config.yml
version: 2
# Declare reusable alias

build: &build
  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: build image
        command: docker build -f ${DOCKERFILE} -t php-test:${IMAGE_TAG} .

# Configure Jobs:
jobs:
  php-7.3-cli-alpine:
    working_directory: /app
    docker:
      - image: docker:git
    environment:
      - IMAGE_TAG: 7.3-cli-alpine
      - DOCKERFILE: php-7.3-cli-alpine/Dockerfile
    <<: *build

  php-7.3-cli-stretch:
    working_directory: /app
    docker:
      - image: docker:git
    environment:
      - IMAGE_TAG: 7.3-cli-stretch
      - DOCKERFILE: php-7.3-cli-stretch/Dockerfile
    <<: *build

  php-7.3-fpm-alpine:
    working_directory: /app
    docker:
      - image: docker:git
    environment:
      - IMAGE_TAG: 7.3-fpm-alpine
      - DOCKERFILE: php-7.3-fpm-alpine/Dockerfile
    <<: *build

  php-7.2-cli-alpine:
    working_directory: /app
    docker:
      - image: docker:git
    environment:
      - IMAGE_TAG: 7.2-cli-alpine
      - DOCKERFILE: php-7.2-cli-alpine/Dockerfile
    <<: *build

  php-7.2-cli-stretch:
    working_directory: /app
    docker:
      - image: docker:git
    environment:
      - IMAGE_TAG: 7.2-cli-stretch
      - DOCKERFILE: php-7.2-cli-stretch/Dockerfile
    <<: *build

  php-7.2-fpm-alpine:
    working_directory: /app
    docker:
      - image: docker:git
    environment:
      - IMAGE_TAG: 7.2-fpm-alpine
      - DOCKERFILE: php-7.2-fpm-alpine/Dockerfile
    <<: *build

  php-7.1-cli-alpine:
    working_directory: /app
    docker:
      - image: docker:git
    environment:
      - IMAGE_TAG: 7.1-cli-alpine
      - DOCKERFILE: php-7.1-cli-alpine/Dockerfile
    <<: *build

  php-7.1-cli-stretch:
    working_directory: /app
    docker:
      - image: docker:git
    environment:
      - IMAGE_TAG: 7.1-cli-stretch
      - DOCKERFILE: php-7.1-cli-stretch/Dockerfile
    <<: *build

  php-7.1-fpm-alpine:
    working_directory: /app
    docker:
      - image: docker:git
    environment:
      - IMAGE_TAG: 7.1-fpm-alpine
      - DOCKERFILE: php-7.1-fpm-alpine/Dockerfile
    <<: *build

  php-7.3-cli-alpine-codeception:
    working_directory: /app
    docker:
      - image: docker:git
    environment:
      - IMAGE_TAG: 7.3-cli-alpine-codeception
      - DOCKERFILE: php-7.3-cli-alpine-codeception/Dockerfile
    <<: *build

# Define the workflow
workflows:
  version: 2
  # Always build images
  build:
    jobs:
      - php-7.3-cli-alpine
      - php-7.3-cli-stretch
      - php-7.3-fpm-alpine
      - php-7.2-cli-alpine
      - php-7.2-cli-stretch
      - php-7.2-fpm-alpine
      - php-7.1-cli-alpine
      - php-7.1-cli-stretch
      - php-7.1-fpm-alpine
      - php-7.3-cli-alpine-codeception:
          requires:
            - php-7.3-cli-alpine

