# .circleci/config.yml
version: 2.1

# Define reusable command
commands:
  build_image:
    description: Build docker image
    parameters:
      image_tag:
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image << parameters.image_tag >>
          command: docker build -f php-<< parameters.image_tag >> -t php-test:<< parameters.image_tag >> .

# Declare reusable alias
build: &build
  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: build image
        command: docker build -f ${DOCKERFILE} -t php-test:${IMAGE_TAG} .

# Configure Jobs:
jobs:
  php-7-3-cli-alpine:
    working_directory: /app
    docker:
      - image: docker:git
    steps:
      - build_image:
          image_tag: 7.3-cli-alpine
  #          dockerfile: php-7.3-cli-alpine/Dockerfile

  php-7-3-cli-stretch:
    working_directory: /app
    docker:
      - image: docker:git
    steps:
      - build_image:
          image_tag: 7.3-cli-stretch
  #          dockerfile: php-7.3-cli-stretch/Dockerfile

  php-7-3-fpm-alpine:
    working_directory: /app
    docker:
      - image: docker:git
    steps:
      - build_image:
          image_tag: 7.3-fpm-alpine
  #          dockerfile: php-7.3-fpm-alpine/Dockerfile

  php-7-2-cli-alpine:
    working_directory: /app
    docker:
      - image: docker:git
    environment:
      - IMAGE_TAG: 7.2-cli-alpine
      - DOCKERFILE: php-7.2-cli-alpine/Dockerfile
    <<: *build

  php-7-2-cli-stretch:
    working_directory: /app
    docker:
      - image: docker:git
    environment:
      - IMAGE_TAG: 7.2-cli-stretch
      - DOCKERFILE: php-7.2-cli-stretch/Dockerfile
    <<: *build

  php-7-2-fpm-alpine:
    working_directory: /app
    docker:
      - image: docker:git
    environment:
      - IMAGE_TAG: 7.2-fpm-alpine
      - DOCKERFILE: php-7.2-fpm-alpine/Dockerfile
    <<: *build

  php-7-1-cli-alpine:
    working_directory: /app
    docker:
      - image: docker:git
    environment:
      - IMAGE_TAG: 7.1-cli-alpine
      - DOCKERFILE: php-7.1-cli-alpine/Dockerfile
    <<: *build

  php-7-1-cli-stretch:
    working_directory: /app
    docker:
      - image: docker:git
    environment:
      - IMAGE_TAG: 7.1-cli-stretch
      - DOCKERFILE: php-7.1-cli-stretch/Dockerfile
    <<: *build

  php-7-1-fpm-alpine:
    working_directory: /app
    docker:
      - image: docker:git
    environment:
      - IMAGE_TAG: 7.1-fpm-alpine
      - DOCKERFILE: php-7.1-fpm-alpine/Dockerfile
    <<: *build

  php-7-3-cli-alpine-codeception:
    working_directory: /app
    docker:
      - image: docker:git
    environment:
      - IMAGE_TAG: 7.3-cli-alpine-codeception
      - DOCKERFILE: php-7.3-cli-alpine-codeception/Dockerfile
    <<: *build

  builds_completed:
    docker:
      - image: docker:git
    steps:
      - run: echo "Builds completed with success"

# Define the workflow
workflows:
  version: 2
  # Always build images
  build:
    jobs:
      - php-7-3-cli-alpine
      - php-7-3-cli-stretch
      - php-7-3-fpm-alpine
      - php-7-2-cli-alpine
      - php-7-2-cli-stretch
      - php-7-2-fpm-alpine
      - php-7-1-cli-alpine
      - php-7-1-cli-stretch
      - php-7-1-fpm-alpine
      - php-7-3-cli-alpine-codeception:
          requires:
            - php-7-3-cli-alpine
      - builds_completed:
          requires:
            - php-7-3-cli-alpine
            - php-7-3-cli-stretch
            - php-7-3-fpm-alpine
            - php-7-2-cli-alpine
            - php-7-2-cli-stretch
            - php-7-2-fpm-alpine
            - php-7-1-cli-alpine
            - php-7-1-cli-stretch
            - php-7-1-fpm-alpine
            - php-7-3-cli-alpine-codeception


